version: "2"

services:
  app:
    image: numberwang:latest
    environment:
      - PORT=8000
    volumes:
      - .:/go/src/Numberwang
    ports:
      - "8000:8000"
    working_dir: /go/src/Numberwang
    command: go run main.go

